export const sections = [
  { id: 'opening', title: '開場與挑戰', range: [1, 5], accent: '競速開始：從集集到花蓮，爭取地震波抵達前的每一秒。' },
  { id: 'risk', title: '臺灣地震環境與風險', range: [6, 13], accent: '板塊聚合、頻繁地震、近年嘉南地區災害案例。' },
  { id: 'center', title: '地震測報中心與即時觀測', range: [14, 17], accent: '24小時作業、巨量即時資料與監測畫面。' },
  { id: 'eew', title: '強震即時警報', range: [18, 23], accent: 'P波快、S波強；警報時效從102秒壓縮到7秒。' },
  { id: 'limits', title: '科技極限與複合型災害', range: [24, 35], accent: '深震、誤報、漏報與海嘯警報作業。' },
  { id: 'response', title: '掌握關鍵應變與整備', range: [36, 42], accent: '最後一哩路、防救災單位串接與防災教育宣導。' },
  { id: 'ai', title: 'AI地震預警與結語', range: [43, 50], accent: '機器學習預估震度、現地型預警與公私協力。' }
]

export const slides = [
{n:1,title:'臺灣地震預警系統的演進與發展',section:'opening',text:'嘉義縣政府115度天然災害停止上班及上課通報作業講習。陳達毅 科長，中央氣象署地震測報中心。'},
{n:2,title:'在地震中心工作面臨的挑戰',section:'opening',text:'媒體報導與地震中心面臨快速說明、即時回應的挑戰。'},
{n:3,title:'競速開始',section:'opening',text:'1999.9.21集集地震與2024.4.3花蓮地震，地震波與預警競速。'},
{n:4,title:'競速開始：2024.4.3花蓮地震',section:'opening',text:'以花蓮地震監測畫面與震度圖呈現即時觀測。'},
{n:5,title:'利用即時逐秒觀測震度輔助地震預警系統',section:'opening',text:'地震災害必須同時考慮強度與持續時間；第一報、第二報與逐秒震度資料。'},
{n:6,title:'臺灣的地震環境與風險',section:'risk',text:'菲律賓海板塊與歐亞大陸板塊每年約7至8公分聚合，臺灣地震頻繁。'},
{n:7,title:'臺灣的地震環境與風險-GNSS絕對水平速度場',section:'risk',text:'GNSS速度場與應變場顯示臺灣受到板塊擠壓。'},
{n:8,title:'臺灣的地震環境與風險',section:'risk',text:'1900年以來大規模災害地震與統計：每天約100個地震，每年約100個顯著有感地震。'},
{n:9,title:'臺灣的地震環境與風險',section:'risk',text:'地震分布圖與時間序列統計圖。'},
{n:10,title:'過去10年災害地震',section:'risk',text:'美濃、花蓮、池上、大埔等災害地震案例與傷亡、房屋損失。'},
{n:11,title:'近年來嘉南地區災害性地震：甲仙',section:'risk',text:'2010年3月4日M6.3 JiaXian Earthquake。'},
{n:12,title:'近年來嘉南地區災害性地震：美濃',section:'risk',text:'2016年2月6日M6.6 Meinong Earthquake。'},
{n:13,title:'近年來嘉南地區災害性地震：大埔',section:'risk',text:'2025年1月21日M6.4 Dapu Earthquake。'},
{n:14,title:'地震測報中心工作環境',section:'center',text:'員工人數約60人，24小時作業，全年無休。'},
{n:15,title:'地震測報中心工作環境',section:'center',text:'值班環境與監測螢幕。'},
{n:16,title:'地震監測畫面',section:'center',text:'地震發生時值班同仁可立刻掌握相關資訊。'},
{n:17,title:'即時地震觀測網-巨量資料',section:'center',text:'約3000個觀測頻道，每頻道接收100Hz取樣率資料。'},
{n:18,title:'強震即時警報原理',section:'eew',text:'利用P波資訊快速推估地震大小，於災害性震波抵達前收到警報。'},
{n:19,title:'強震即時警報發布條件與管道',section:'eew',text:'國家級警報、電視、網路推播等發布管道與條件。'},
{n:20,title:'強震即時警報：2024.4.3花蓮地震',section:'eew',text:'花蓮地震報告與震度圖。'},
{n:21,title:'國家級警報',section:'eew',text:'2024.4.3花蓮地震手機細胞廣播警報示例。'},
{n:22,title:'網路推播與電視臺推播',section:'eew',text:'強震即時警報在網路與電視臺的呈現。'},
{n:23,title:'與地震波賽跑',section:'eew',text:'警報發布時效從102秒縮短至7秒，盲區半徑由35公里縮減至25公里。'},
{n:24,title:'科技極限與複合型災害 – 深震',section:'limits',text:'以114年12月27日規模7.0地震為例，第一報與第二報比較。'},
{n:25,title:'科技極限與複合型災害 – 誤報',section:'limits',text:'111年9月18日雲嘉南地區誤發國家級警報。'},
{n:26,title:'科技極限與複合型災害 – 誤報',section:'limits',text:'地震報告與警報畫面。'},
{n:27,title:'科技極限與複合型災害 – 誤報',section:'limits',text:'短時間內發生兩個地震造成誤報。'},
{n:28,title:'科技極限與複合型災害 – 漏報',section:'limits',text:'兩個地震相差4秒，預警系統僅處理第一個地震，造成漏報。'},
{n:29,title:'科技極限與複合型災害 – 漏報',section:'limits',text:'測站波形示例。'},
{n:30,title:'科技極限與複合型災害 – 海嘯',section:'limits',text:'海嘯形成條件：地震規模夠大、震源深度夠淺、海床垂直錯動。'},
{n:31,title:'臺灣海嘯威脅',section:'limits',text:'琉球海溝、亞普海溝、馬尼拉海溝。'},
{n:32,title:'臺灣海嘯警戒分區與波高分級',section:'limits',text:'6個海嘯警戒分區，預估波高分為4級。'},
{n:33,title:'海嘯警報範例',section:'limits',text:'海嘯警報報文內容、分區、到達時間、波高分級與地震資訊。'},
{n:34,title:'海嘯警報實例：2024花蓮地震',section:'limits',text:'2024/4/3 M7.2花蓮地震後海嘯警報發布、更新與解除。'},
{n:35,title:'海嘯警報實例：堪察加地震',section:'limits',text:'114年7月30日堪察加半島東部外海M8.8地震之海嘯消息、警訊、警報與解除。'},
{n:36,title:'掌握關鍵應變與整備 – 最後一哩路',section:'response',text:'地震報告、強震警報、震度速報與多種發布通道。'},
{n:37,title:'直送防救災需求單位',section:'response',text:'地震速報資訊直接發送單位超過4500個，包含學校、公路、軌道與防救災單位。'},
{n:38,title:'掌握關鍵應變與整備',section:'response',text:'防救災單位接獲地震資訊後的應變與整備流程。'},
{n:39,title:'防災教育宣導',section:'response',text:'居家、避難、戶外與地震三步驟宣導。'},
{n:40,title:'防災教育宣導',section:'response',text:'國家防災日與校園防災演練宣導。'},
{n:41,title:'防災教育宣導：海嘯預警',section:'response',text:'海嘯警報、警訊、消息與避難行動建議。'},
{n:42,title:'常見Q&A – 民間業者APP比較快收到警報？',section:'response',text:'以114年12月27日規模7.0地震與村里地震廣播預警系統為例。'},
{n:43,title:'地震預警系統演算邏輯',section:'ai',text:'採用機器學習模型預估震度：波形輸入、特徵萃取、分類與輸出。'},
{n:44,title:'地震預警系統演算邏輯',section:'ai',text:'使用初期P波與AI模型提供預警。'},
{n:45,title:'機器學習模型預估震度—實際案例',section:'ai',text:'實際地震報告與LINE Notify推播案例。'},
{n:46,title:'即時逐秒觀測震度輔助地震預警系統',section:'ai',text:'2024年4月3日逐秒震度與警報時間。'},
{n:47,title:'即時逐秒觀測震度輔助地震預警系統',section:'ai',text:'利用地震發生初期觀測震度分佈評估是否發布警報。'},
{n:48,title:'結語 - 持續精進地震速警報效能',section:'ai',text:'AI現地型預警與預警發布精緻化。'},
{n:49,title:'結語 - 持續加強公私協力合作',section:'ai',text:'公私協力、多管道傳遞示意圖。'},
{n:50,title:'謝謝聆聽，敬請指教',section:'ai',text:'結尾頁，展示測站設備與工作照片。'}
]
